name: ecr
on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Teststep
        run: |
          ls && cat Dockerfile
      - uses: kciter/aws-ecr-action@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: mentorship-platform
          region: ap-southeast-1
          tags: latest,${{ github.sha }}
          create_repo: true
